{
  "code": 200,
  "data": {
      "classname": "欧美女歌手",
      "classid": 8,
      "singers": {
          "page": 1,
          "pagesize": 30,
          "total": null,
          "list": {
              "timestamp": 1558957125,
              "info": [
                  {
                      "heatoffset": -14,
                      "sortoffset": -51,
                      "singername": "Taylor Swift",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 17923,
                      "singerid": 34450,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20190417/20190417194827175.jpg",
                      "fanscount": 1582740,
                      "is_settled": 1
                  },
                  {
                      "heatoffset": 104,
                      "sortoffset": 183,
                      "singername": "Billie Eilish",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 8843,
                      "singerid": 295991,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20190401/20190401182307531.jpg",
                      "fanscount": 114191,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -45,
                      "sortoffset": -18,
                      "singername": "Lady Gaga",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 5647,
                      "singerid": 83709,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20180724/20180724154712780.jpg",
                      "fanscount": 496494,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": 5,
                      "sortoffset": -106,
                      "singername": "Adele",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 4587,
                      "singerid": 36365,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20170316/20170316184254744.jpg",
                      "fanscount": 522718,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -10,
                      "sortoffset": -12,
                      "singername": "Avril Lavigne",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 4308,
                      "singerid": 36363,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20180920/20180920191146880.jpg",
                      "fanscount": 696337,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -3,
                      "sortoffset": 78,
                      "singername": "Selena Gomez",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 3830,
                      "singerid": 78870,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20170808/20170808155612295.jpg",
                      "fanscount": 330750,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -59,
                      "sortoffset": 20,
                      "singername": "Sia",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 3423,
                      "singerid": 61886,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20150126/20150126180315786375.jpg",
                      "fanscount": 319561,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -30,
                      "sortoffset": -11,
                      "singername": "Britney Spears",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 3307,
                      "singerid": 38344,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20160429/20160429120315827.jpg",
                      "fanscount": 205815,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": 9,
                      "sortoffset": -14,
                      "singername": "Mariah Carey",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 2611,
                      "singerid": 54681,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20160429/20160429120415496.jpg",
                      "fanscount": 114857,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -31,
                      "sortoffset": -12,
                      "singername": "Rihanna",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 2423,
                      "singerid": 60024,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20180112/20180112182114478.jpg",
                      "fanscount": 501989,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -170,
                      "sortoffset": 5,
                      "singername": "Katie Sky",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 1915,
                      "singerid": 158189,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20150714/20150714134036168301.jpg",
                      "fanscount": 31622,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -83,
                      "sortoffset": 24,
                      "singername": "Ariana Grande",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 1489,
                      "singerid": 90471,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20190226/20190226190831116.jpg",
                      "fanscount": 268516,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -32,
                      "sortoffset": -17,
                      "singername": "Beyoncé",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 1370,
                      "singerid": 38343,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20190419/20190419154130687.jpg",
                      "fanscount": 113281,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": 62,
                      "sortoffset": -2,
                      "singername": "Céline Dion",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 1204,
                      "singerid": 40324,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20140227/20140227163545223573.jpg",
                      "fanscount": 98461,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -99,
                      "sortoffset": -28,
                      "singername": "Colbie Caillat",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 1158,
                      "singerid": 40331,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20160429/20160429120319899.jpg",
                      "fanscount": 57844,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -90,
                      "sortoffset": -11,
                      "singername": "Katy Perry",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 1134,
                      "singerid": 51504,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20190423/20190423112202213.jpg",
                      "fanscount": 228420,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": 77,
                      "sortoffset": -19,
                      "singername": "Sarah Brightman",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 974,
                      "singerid": 61876,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20181023/20181023165755387.jpg",
                      "fanscount": 72951,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -137,
                      "sortoffset": 63,
                      "singername": "MØ",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 882,
                      "singerid": 153160,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20161018/20161018195907862031.jpg",
                      "fanscount": 28183,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -69,
                      "sortoffset": 4,
                      "singername": "Jessie J",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 880,
                      "singerid": 83977,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20190312/20190312103136797.jpg",
                      "fanscount": 254733,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": 0,
                      "sortoffset": -27,
                      "singername": "Madonna",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 778,
                      "singerid": 54682,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20190418/20190418004904356.jpg",
                      "fanscount": 34758,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -88,
                      "sortoffset": -153,
                      "singername": "Lenka",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 705,
                      "singerid": 52701,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20171222/20171222103312358.jpg",
                      "fanscount": 231276,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -6,
                      "sortoffset": -31,
                      "singername": "Enya",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 666,
                      "singerid": 44283,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20161011/20161011163756938.jpg",
                      "fanscount": 34453,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -127,
                      "sortoffset": -144,
                      "singername": "Kelly Clarkson",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 654,
                      "singerid": 51501,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20180128/20180128225059878.jpg",
                      "fanscount": 192788,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": 57,
                      "sortoffset": -46,
                      "singername": "Whitney Houston",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 590,
                      "singerid": 66588,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20140318/20140318181856754561.jpg",
                      "fanscount": 42068,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -54,
                      "sortoffset": -14,
                      "singername": "Nicki Minaj",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 571,
                      "singerid": 83734,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20180810/20180810160346729.jpg",
                      "fanscount": 106192,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -5,
                      "sortoffset": -9,
                      "singername": "Lana Del Rey",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 542,
                      "singerid": 84347,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20190110/20190110161816870.jpg",
                      "fanscount": 98689,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -82,
                      "sortoffset": 13,
                      "singername": "Carly Rae Jepsen",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 537,
                      "singerid": 84672,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20190227/20190227181559110.jpg",
                      "fanscount": 358706,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -89,
                      "sortoffset": 28,
                      "singername": "Bebe Rexha",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 464,
                      "singerid": 156221,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20161118/20161118171525312.jpg",
                      "fanscount": 44928,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": -72,
                      "sortoffset": 22,
                      "singername": "Halsey",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 449,
                      "singerid": 175711,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20181130/20181130114537759.jpg",
                      "fanscount": 65325,
                      "is_settled": 0
                  },
                  {
                      "heatoffset": 17,
                      "sortoffset": -91,
                      "singername": "Rezz",
                      "intro": "",
                      "albumcount": 0,
                      "songcount": 0,
                      "banner_url": "",
                      "mvcount": 0,
                      "heat": 446,
                      "singerid": 725593,
                      "imgurl": "http://singerimg.kugou.com/uploadpic/softhead/{size}/20170707/20170707162113766.jpg",
                      "fanscount": 17016,
                      "is_settled": 0
                  }
              ],
              "total": 5384
          }
      }
  },
  "msg": ""
}